versions: 2.1
jobs:
  build:
    working_directory: ~/circleci_tutorial
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
            pip install coverage==5.0a5
      - run:
          command: |
            coverage run
            coverage report
            coverage html 
      - store_test_results:
          path: htmlcov